export const API_PREFIX = '/api/v1';

export const USER_ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLINIC_OWNER: 'CLINIC_OWNER',
  DESK_MANAGER: 'DESK_MANAGER',
  RECEPTIONIST: 'RECEPTIONIST',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  BILLING_STAFF: 'BILLING_STAFF',
  PHARMACIST: 'PHARMACIST',
  LAB_STAFF: 'LAB_STAFF',
  PATIENT: 'PATIENT',
});

export const USER_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
});

export const PERMISSIONS = Object.freeze({
  PATIENT_CREATE: 'patient.create',
  PATIENT_VIEW: 'patient.view',
  PATIENT_UPDATE: 'patient.update',
  PATIENT_MERGE: 'patient.merge',
  APPOINTMENT_CREATE: 'appointment.create',
  APPOINTMENT_VIEW: 'appointment.view',
  APPOINTMENT_UPDATE: 'appointment.update',
  APPOINTMENT_CANCEL: 'appointment.cancel',
  QUEUE_VIEW: 'queue.view',
  QUEUE_MANAGE: 'queue.manage',
  QUEUE_OVERRIDE: 'queue.override',
  ENCOUNTER_VIEW: 'encounter.view',
  ENCOUNTER_CREATE: 'encounter.create',
  ENCOUNTER_UPDATE: 'encounter.update',
  ENCOUNTER_COMPLETE: 'encounter.complete',
  VITALS_VIEW: 'vitals.view',
  VITALS_CREATE: 'vitals.create',
  VITALS_UPDATE: 'vitals.update',
  DIAGNOSIS_VIEW: 'diagnosis.view',
  DIAGNOSIS_CREATE: 'diagnosis.create',
  DIAGNOSIS_UPDATE: 'diagnosis.update',
  PRESCRIPTION_VIEW: 'prescription.view',
  PRESCRIPTION_CREATE: 'prescription.create',
  PRESCRIPTION_UPDATE: 'prescription.update',
  PRESCRIPTION_PRINT: 'prescription.print',
  BILLING_VIEW: 'billing.view',
  BILLING_CREATE: 'billing.create',
  BILLING_UPDATE: 'billing.update',
  BILLING_REFUND: 'billing.refund',
  PAYMENT_VIEW: 'payment.view',
  PAYMENT_COLLECT: 'payment.collect',
  PAYMENT_REFUND: 'payment.refund',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_UPDATE: 'inventory.update',
  INVENTORY_ADJUST: 'inventory.adjust',
  LAB_ORDER: 'lab.order',
  LAB_VIEW: 'lab.view',
  LAB_RESULT_CREATE: 'lab.result.create',
  LAB_RESULT_VERIFY: 'lab.result.verify',
  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DEACTIVATE: 'staff.deactivate',
  REPORT_OPERATIONAL: 'report.operational',
  REPORT_FINANCIAL: 'report.financial',
  REPORT_CLINICAL: 'report.clinical',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',
  AUDIT_VIEW: 'audit.view',
  BACKUP_RUN: 'backup.run',
  BACKUP_RESTORE: 'backup.restore',
});

const allPermissions = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = Object.freeze({
  [USER_ROLES.SUPER_ADMIN]: allPermissions,
  [USER_ROLES.CLINIC_OWNER]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.REPORT_OPERATIONAL,
    PERMISSIONS.REPORT_FINANCIAL,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [USER_ROLES.DESK_MANAGER]: [
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.QUEUE_OVERRIDE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.REPORT_OPERATIONAL,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [USER_ROLES.RECEPTIONIST]: [
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.PAYMENT_COLLECT,
  ],
  [USER_ROLES.DOCTOR]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ENCOUNTER_UPDATE,
    PERMISSIONS.ENCOUNTER_COMPLETE,
    PERMISSIONS.VITALS_VIEW,
    PERMISSIONS.DIAGNOSIS_VIEW,
    PERMISSIONS.DIAGNOSIS_CREATE,
    PERMISSIONS.DIAGNOSIS_UPDATE,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,
    PERMISSIONS.PRESCRIPTION_PRINT,
    PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.REPORT_CLINICAL,
  ],
  [USER_ROLES.NURSE]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_MANAGE,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.VITALS_VIEW,
    PERMISSIONS.VITALS_CREATE,
    PERMISSIONS.VITALS_UPDATE,
    PERMISSIONS.PRESCRIPTION_VIEW,
  ],
  [USER_ROLES.BILLING_STAFF]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_COLLECT,
    PERMISSIONS.REPORT_FINANCIAL,
  ],
  [USER_ROLES.PHARMACIST]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.BILLING_VIEW,
  ],
  [USER_ROLES.LAB_STAFF]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_RESULT_CREATE,
    PERMISSIONS.LAB_RESULT_VERIFY,
  ],
  [USER_ROLES.PATIENT]: [],
});

export const QUEUE_STATES = Object.freeze({
  REGISTERED: 'REGISTERED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  WAITING: 'WAITING',
  VITALS_PENDING: 'VITALS_PENDING',
  VITALS_COMPLETE: 'VITALS_COMPLETE',
  READY_FOR_DOCTOR: 'READY_FOR_DOCTOR',
  IN_CONSULTATION: 'IN_CONSULTATION',
  CONSULTATION_COMPLETE: 'CONSULTATION_COMPLETE',
  BILLING_PENDING: 'BILLING_PENDING',
  PAID: 'PAID',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
  CANCELLED: 'CANCELLED',
  ON_HOLD: 'ON_HOLD',
  REFERRED: 'REFERRED',
  LAB_PENDING: 'LAB_PENDING',
  PHARMACY_PENDING: 'PHARMACY_PENDING',
});

export const QUEUE_TRANSITIONS = Object.freeze({
  REGISTERED: ['WAITING', 'CANCELLED'],
  PAYMENT_PENDING: ['CANCELLED'],
  WAITING: ['VITALS_PENDING', 'READY_FOR_DOCTOR', 'ON_HOLD', 'NO_SHOW', 'CANCELLED'],
  VITALS_PENDING: ['VITALS_COMPLETE', 'ON_HOLD', 'CANCELLED'],
  VITALS_COMPLETE: ['READY_FOR_DOCTOR', 'ON_HOLD'],
  READY_FOR_DOCTOR: ['IN_CONSULTATION', 'ON_HOLD', 'NO_SHOW'],
  IN_CONSULTATION: ['CONSULTATION_COMPLETE', 'LAB_PENDING', 'REFERRED', 'ON_HOLD'],
  CONSULTATION_COMPLETE: ['BILLING_PENDING', 'PHARMACY_PENDING', 'COMPLETED'],
  LAB_PENDING: ['READY_FOR_DOCTOR', 'BILLING_PENDING', 'COMPLETED'],
  PHARMACY_PENDING: ['BILLING_PENDING', 'PAID', 'COMPLETED'],
  BILLING_PENDING: ['PAID', 'ON_HOLD'],
  PAID: ['COMPLETED'],
  ON_HOLD: ['WAITING', 'READY_FOR_DOCTOR', 'IN_CONSULTATION', 'CANCELLED'],
  REFERRED: ['BILLING_PENDING', 'COMPLETED'],
  COMPLETED: [],
  NO_SHOW: ['WAITING', 'CANCELLED'],
  CANCELLED: [],
});

export const APPOINTMENT_TYPES = Object.freeze([
  'NEW_CONSULTATION',
  'FOLLOW_UP',
  'PROCEDURE',
  'REVIEW',
  'LAB_ONLY',
  'VACCINATION',
  'CUSTOM',
]);

export const APPOINTMENT_STATUSES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  CHECKED_IN: 'CHECKED_IN',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
});

export const VISIT_PRIORITIES = Object.freeze({
  ROUTINE: 0,
  URGENT: 50,
  EMERGENCY: 100,
});

export const ENCOUNTER_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
});

export const INVOICE_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
});

export const PAYMENT_METHODS = Object.freeze(['CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER']);

export const INVENTORY_TRANSACTION_TYPES = Object.freeze([
  'PURCHASE',
  'DISPENSE',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
]);

export const LAB_STATUSES = Object.freeze({
  ORDERED: 'ORDERED',
  SAMPLE_PENDING: 'SAMPLE_PENDING',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  PROCESSING: 'PROCESSING',
  RESULT_READY: 'RESULT_READY',
  VERIFIED: 'VERIFIED',
  CANCELLED: 'CANCELLED',
});

export const PATIENT_FIELDS = Object.freeze({
  REQUIRED: ['fullName', 'mobile', 'gender'],
  IDENTITY: ['openemrPatientId', 'fullName', 'mobile', 'dateOfBirth'],
  OPTIONAL: [
    'age',
    'email',
    'address',
    'city',
    'state',
    'pinCode',
    'emergencyContact',
    'bloodGroup',
    'preferredLanguage',
    'governmentId',
    'abhaId',
  ],
});

export const APPOINTMENT_FIELDS = Object.freeze([
  'patientId',
  'doctorId',
  'date',
  'time',
  'reason',
  'visitType',
  'notes',
  'referralSource',
  'reminderPreference',
]);

export const QUEUE_NAMES = Object.freeze({
  NOTIFICATIONS: 'clinicos-notifications',
});

export const NOTIFICATION_JOB_TYPES = Object.freeze({
  APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
  FOLLOW_UP_REMINDER: 'FOLLOW_UP_REMINDER',
  LAB_RESULT_READY: 'LAB_RESULT_READY',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
});
